### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Frankdroid7** [buildwiththeta/buildwiththeta#203] opened 2023-07-25 22:51 UTC
# **Title:** 

Need to Hot Restart the app multiple times to see changes made.

## **Description:** 

When I make a change on Theta's dashboard, I need to Hot Restart the app 4 times to see the changes I made.
When I reload it once, I always get this `[error] Error fetching styles: Exception: type 'Null' is not a subtype of type 'String'`
When I reload it the second time, I always get `Exception: Bad state: No element`
When I reload it the third time, the first error shows again.
Then it works (shows my latest changes) on the fourth Hot Restart.

---

## **Flutter Environment:** 

[!] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E261 darwin-arm64, locale en-NG)
    • Flutter version 3.10.4 on channel stable at /Users/frankdroid/Development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.3/libexec/bin/dart, which is not inside your current Flutter
      SDK checkout at /Users/frankdroid/Development/flutter. Consider adding /Users/frankdroid/Development/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (7 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

## **App Version:** 

N/A

## **Device Information:** 

iPhone 14 Pro - iOS 16.4

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. Make UI changes on the dashboard online.
2. Hot Restart the simulator (iphone) to reflect the changes.
3. Notice it doesn't work the first 3 times you reload. Only works the fourth time.
4. 

## **Expected Behavior:** 

I expected the changes to be reflected the first time I reload the app

## **Actual Behavior:** 

The app didn't reflect the changes until I reloaded it 10 times.

## **Logs:** 

(https://gist.github.com/Frankdroid7/eaca6323c141be30cb97aae74780fc4d)

## **Screenshots:**

I get this when I Hot Restart the app the first time after making changes on the dashboard online:
<img width="1012" alt="Screenshot 2023-07-25 at 23 47 08" src="https://github.com/buildwiththeta/buildwiththeta/assets/30746679/72df9b68-3644-4aa0-9100-37cc297271c2">

I get this the second time I Hot Restart the app:

<img width="345" alt="Screenshot 2023-07-25 at 23 47 51" src="https://github.com/buildwiththeta/buildwiththeta/assets/30746679/1f70dad1-4274-4cb7-938e-2eb70b0e0721">

And the third time, I get the first error.
The fourth time, it works.

## **Additional Context:** 

N/A

## **Possible Solution:** 

N/A

**Comment by andreabuttarelli** [comment] 2023-07-26 12:39
Hi @Frankdroid7, thank you for the report. Can you confirm that you don't use `preload` attribute inside `Theta.initialize`? Also, do you use `cacheEnabled: false`?
Running the same project with Flutter Web (chrome), is the situation the same?

**Comment by Frankdroid7** [comment] 2023-07-26 20:15
Hello @andreabuttarelli 
1. No I'm not using `preload` attribute.
2. No I'm not using `cacheEnabled: false`
3. Yes I just tested it out on chrome now and I'm experiencing the same issue.

**My observation:**
It feels as if it takes some time when I make a change on the dashboard, for the dashboard to actually 'propagate' that change to the server for the application to notice or 'react' to a new change because when I reload it, the error I get is:
`[error] Error fetching styles: Exception: Expected a value of type 'String', but got one of type 'Null'`. 
Seems the json response returns `null` instead of a string.

This is the error I got when I ran the app on chrome. Same with mobile, I had to reload it about 4 times for me to see the updated changes. 

<img width="1107" alt="Screenshot 2023-07-26 at 21 10 55" src="https://github.com/buildwiththeta/buildwiththeta/assets/30746679/e87e25a4-9071-4af8-a49a-26a16a5ac1e3">

I will happy to help if you need any further information😊

**Comment by andreabuttarelli** [comment] 2023-07-26 20:23
Thank you for your helpfulness @Frankdroid7, the additional details made me understand much more. I think I found the cause of this error. Can you tell me if it works well with `cacheEnable: false`?

Regarding the propagation of the changes, they follow the cache duration that we set in the initialize() method

**Comment by andreabuttarelli** [comment] 2023-07-27 08:18
I will post the fix for this issue today.
Regarding `cacheEnabled: false` it is recommended in development, but if left false in production you might exceed the maximum limit of api calls (the free tier includes up to 1k/month) as it looks for UI updates every time the client app starts.

**Comment by andreabuttarelli** [comment] 2023-07-28 17:00
It’s fixed :) You can use `Theta.initialize(connectionMode: ConnectionMode.cached, …)`

**Comment by Frankdroid7** [comment] 2023-07-28 17:09
Just tested it. It works fine now 👍🏽
How long does it take the Cache to expire?

**Comment by andreabuttarelli** [comment] 2023-07-29 00:07
You can set a custom cache extension inside `Theta.initialize(…, cacheExtension: 43200)`. Default 12h. The value is in seconds.

**Closed** 2023-07-29 00:07 UTC

**Comment by Frankdroid7** [comment] 2023-07-29 00:10
Alright cool ✌🏽
